### PR TITLE
Add code style guidelines link to main README.

### PR DESCRIPTION
**Pull request by awwad**
Does just that (;

While the code style guidelines was linked to from the [SSL website landing page](https://ssl.engineering.nyu.edu/collaborate), it wasn't in the overview README for this repo.

### CODE REVIEW

**Comment by aaaaalbert** [comment]
A really irrelevant observation here: The other items in the list end with a period; your new one doesn't.

**Comment by awwad** [comment]
Commit amended. Hehehe

**Comment by aaaaalbert** [comment]
Well and sneakily done :)

I approve!

**Comment by awwad** [comment]
Sneaky is the part where I edited your previous message to fix the "sneakily" typo. 🙊

**Comment by vladimir-v-diaz** [comment]
banana-peel-slip

**Comment by vladimir-v-diaz** [comment]
Albert, I think Seb just caught you slipping.  I wouldn't object to a lab guideline against ninja edits.

**Comment by aaaaalbert** [comment]
I stanned currectid. Thanks gentleninjas 😆

**Pull request merged**
